### ISSUE TITLE
update tutorial

### ISSUE THREAD

**Issue by elitan** [apollostack/apollo-tutorial-kit#23]
The following is not enough for me to get the new apollo-server to work.

> To get to the current version, follow the tutorial, and then update following this migration guide.

**It would be much easier if this repository had an up to date working example on how to get started with the latest apollo-server.**

Things I have trouble with while trying to upgrade:
- online editor gone at localhost:port/graphql ("Apollo Server supports only POST requests.")
- Error when trying POST request. I am posting to the localhost:port/graphql with raw JSON (application/json) using [Postman](https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop):

```
SyntaxError: Unexpected token U in JSON at position 4
<br> &nbsp; &nbsp;at Object.parse (native)
<br> &nbsp; &nbsp;at parse (/home/eli/repos/apollo-graphql-rest-example/node_modules/body-parser/lib/types/json.js:88:17)
<br> &nbsp; &nbsp;at /home/eli/repos/apollo-graphql-rest-example/node_modules/body-parser/lib/read.js:116:18
<br> &nbsp; &nbsp;at invokeCallback (/home/eli/repos/apollo-graphql-rest-example/node_modules/raw-body/index.js:262:16)
<br> &nbsp; &nbsp;at done (/home/eli/repos/apollo-graphql-rest-example/node_modules/raw-body/index.js:251:7)
<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/home/eli/repos/apollo-graphql-rest-example/node_modules/raw-body/index.js:307:7)
<br> &nbsp; &nbsp;at emitNone (events.js:86:13)
<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:185:7)
<br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:934:12)
<br> &nbsp; &nbsp;at _combinedTickCallback (internal/process/next_tick.js:74:11)
```

**Comment by helfer** [comment]
@elitan You can now get GraphiQL on localhost:8080/graphiql (note the extra i).

> It would be much easier if this repository had an up to date working example on how to get started with the latest apollo-server.
Is the server-tutorial-updated branch solution not working for you?

**Comment by elitan** [comment]
Right, thanks for the help @helfer.
